#!/bin/sh

set -e

VERSION=$(cat VERSION)

echo "${CI_REGISTRY}"

docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

docker build -t registry.gitlab.secushare.org/infrastructure/docker-gitlab:latest .

#docker tag $DOCKER_IMAGE $DOCKER_REGISTRY_HOST/$DOCKER_IMAGE:latest
#docker tag $DOCKER_IMAGE $DOCKER_REGISTRY_HOST/$DOCKER_IMAGE:$VERSION

docker push registry.gitlab.secushare.org/infrastructure/docker-gitlab:latest
#docker push $DOCKER_REGISTRY_HOST/$DOCKER_IMAGE:$VERSION
